//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShop.Model
{
    using QuanLyShop.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD : BaseViewModel
    {
        private int _iD;
        public int ID { get => _iD; set { _iD = value; OnPropertyChanged(); } }

        private Nullable<int> _IDHD;
        public Nullable<int> IDHD { get => _IDHD; set { _IDHD = value; OnPropertyChanged(); } }

        private Nullable<int> _IDSP;
        public Nullable<int> IDSP { get => _IDSP; set { _IDSP = value; OnPropertyChanged(); } }

        private Nullable<int> _soLuongDat;
        public Nullable<int> soLuongDat { get => _soLuongDat; set { _soLuongDat = value; OnPropertyChanged(); } }

        private Nullable<double> _thanhTien;
        public Nullable<double> thanhTien { get => _thanhTien; set { _thanhTien = value; OnPropertyChanged(); } }

        public virtual HOADON HOADON { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
