//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShop.Model
{
    using QuanLyShop.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CTHD = new HashSet<CTHD>();
        }

        private int _iD;
        public int ID { get => _iD; set { _iD = value; OnPropertyChanged(); } }

        private Nullable<int> _IDNhanVien;
        public Nullable<int> IDNhanVien { get => _IDNhanVien; set { _IDNhanVien = value; OnPropertyChanged(); } }

        private Nullable<int> _IDKhachHang;
        public Nullable<int> IDKhachHang { get => _IDKhachHang; set { _IDKhachHang = value; OnPropertyChanged(); } }

        private System.DateTime _ngayDat;
        public System.DateTime ngayDat { get => _ngayDat; set { _ngayDat = value; OnPropertyChanged(); } }

        private string _trangThai;
        public string trangThai { get => _trangThai; set { _trangThai = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHD { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
