//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShop.Model
{
    using QuanLyShop.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPHANG : BaseViewModel
    {
        private int _iD;
        public int ID { get => _iD; set { _iD = value; OnPropertyChanged(); } }

        private Nullable<int> _IDNhanVien;
        public Nullable<int> IDNhanVien { get => _IDNhanVien; set { _IDNhanVien = value; OnPropertyChanged(); } }

        private string _maSanPham;
        public string maSanPham { get => _maSanPham; set { _maSanPham = value; OnPropertyChanged(); } }

        private string _tenTheLoai;
        public string tenTheLoai { get => _tenTheLoai; set { _tenTheLoai = value; OnPropertyChanged(); } }

        private string _tenSanPham;
        public string tenSanPham { get => _tenSanPham; set { _tenSanPham = value; OnPropertyChanged(); } }

        private string _size;
        public string size { get => _size; set { _size = value; OnPropertyChanged(); } }

        private Nullable<int> _soLuongNhap;
        public Nullable<int> soLuongNhap { get => _soLuongNhap; set { _soLuongNhap = value; OnPropertyChanged(); } }

        private Nullable<double> _giaNhap;
        public Nullable<double> giaNhap { get => _giaNhap; set { _giaNhap = value; OnPropertyChanged(); } }

        private System.DateTime _ngayNhap;
        public System.DateTime ngayNhap { get => _ngayNhap; set { _ngayNhap = value; OnPropertyChanged(); } }

        private Nullable<double> _tongTien;
        public Nullable<double> tongTien { get => _tongTien; set { _tongTien = value; OnPropertyChanged(); } }

        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
