//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShop.Model
{
    using QuanLyShop.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTHD = new HashSet<CTHD>();
        }

        private int _iD;
        public int ID { get => _iD; set { _iD = value; OnPropertyChanged(); } }

        private int _IDLoai;
        public int IDLoai { get => _IDLoai; set { _IDLoai = value; OnPropertyChanged(); } }

        private string _tenSP;
        public string tenSP { get => _tenSP; set { _tenSP = value; OnPropertyChanged(); } }

        private Nullable<double> _giaSP;
        public Nullable<double> giaSP { get => _giaSP; set { _giaSP = value; OnPropertyChanged(); } }

        private Nullable<int> _soLuong;
        public Nullable<int> soLuong { get => _soLuong; set { _soLuong = value; OnPropertyChanged(); } }

        private string _kichCo;
        public string kichCo { get => _kichCo; set { _kichCo = value; OnPropertyChanged(); } }

        private string _mieuTaSP;
        public string mieuTaSP { get => _mieuTaSP; set { _mieuTaSP = value; OnPropertyChanged(); } }

        private string _imageSP;
        public string imageSP { get => _imageSP; set { _imageSP = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHD { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
